export const ROUTE = {
   WELCOME_PAGE: 'welcomePage',
   MAIN: 'main',
   WELCOME_STORY_1: 'welcome-story-1',
   WELCOME_STORY_2: 'welcome-story-2',
   WELCOME_STORY_3: 'welcome-story-3',
   SIGNUP: 'signup',
   LOGIN: 'login',
   HOME: 'home',
   SEARCH: 'search',
   PROFILE: 'profile',
   TIMELINE: 'timeline',
   BUSINESS_PROFILE: 'businessProfile',
   NON_BUSINESS_PROFILE: 'nonBusinessProfile',
   DETAIL_TIMELINE: 'detail-timeline',
   ADD_POST: 'add-post',
   SETTINGS_ACCOUNT: 'settingsAccount',
   EDIT_ACCOUNT: 'edit-account',
   CHANGE_PASSWORD: 'change-password',
   SETTINGS_NON_BUSINESS: 'settingsNonBusiness',
   PROFILE_BUSINESS: 'profileBusiness',
   PROFILE_NON_BUSINESS: 'profileNonBusiness',
   ADD_FAQ: 'add-faq',
   EDIT_PROFILE: 'edit-profile',
   SETTINGS_OPEN_HOUR: 'settingsOpenHour',
   SETTINGS_LINKS: 'settingsLinks',
   ADD_LINK: 'addLink',
   HELP_CENTER: 'help_center',
   DETAIL_PRODUCT: 'detailProduct',
   PROFILE_DETAIL_PRODUCT: 'profileDetailProduct',

   SUPPORT_ANON: 'supportAnon',
   SUPPORT: 'supportAnon',

   EDIT_POST: 'edit-post',
   ADD_PRODUCT: 'add-product',
   SETTINGS_BUSINESS: 'settingsBusiness',
   NOTIFICATION: 'notification',
   MANAGE_PRODUCT: 'manage-product',
   EDIT_PRODUCT: 'edit-product',
   CATALOG: 'catalog',
   SEARCH_INITIAL: 'searchInitial',
   SPLASH_SCREEN: 'splashScreen',
   TUTORIAL: 'tutorial',
   TUTORIAL_TO_BUSINESS : 'addToBusiness'

}