export const ROUTE = {
   LOGIN: 'login',
   MAIN: 'main',
   HOME: 'home',
   SEARCH: 'search',
   SIGNUP: 'signup',
   ADD_POST: 'add-post',
   ADD_PRODUCT: 'add-product',
   ADD_FAQ: 'add-faq',
   SETTINGS_NON_BUSINESS: 'settingNonBusiness',
   SETTINGS_BUSINESS: 'settingBusiness',
   PROFILE: 'profile',
   NOTIFICATION: 'notification',
   SETTINGS_OPEN_HOUR: 'settingOpenHour',
   SETTINGS_LINKS: 'settingsLinks',
   WELCOME_PAGE: 'welcomePage',
   ADD_LINK: 'addLink',
   TIMELINE: 'timeline',
   DETAIL_TIMELINE: 'detail-timeline',
   CATALOG: 'catalog',
   WELCOME_STORY_1: 'welcome-story-1',
   WELCOME_STORY_2: 'welcome-story-2',
   WELCOME_STORY_3: 'welcome-story-3',
}